### DISCUSSION TITLE
Using local files for icon generation

### DISCUSSION THREAD

**Discussion by Raz1e1** [AngeloAvv/flutter_flavorizr#279] [Q&A] [answered]
From the documentation i understand the i can set the different icons for each flavor.

I set the according icon in the `flavorizr.yaml`

```
flavors:
  banana:
    app:
      name: "Banana App"
    android:
      applicationId: "de.example.banana"
      icon: "./assets/logo.svg"
    ios:
      bundleId: "de.example.banana"
      icon: "./assets/logo.svg"
  apple:
    app:
      name: "Apple App"
    android:
      applicationId: "de.example.apple"
      icon: "./assets/logo.svg"
    ios:
      bundleId: "de.example.apple.internal"
      icon: "./assets/logo.svg"

instructions:
  - flutter:flavors
  - android:buildGradle
  - android:androidManifest
  - android:icons
  - ios:podfile
  - ios:icons
```

When i used `flutter pub run flutter_flavorizr` I got the error message that the file can't be found.

Is it required to have the assets folder available as a zip somewhere remote and use the asset processors to download and extract its content into a temporary directory or should it be possible to pass a local path for a file which should be used as an icon?
