### ISSUE TITLE
settings instruction not working for only android build

### ISSUE THREAD

**Issue by burhankhanzada** [AngeloAvv/flutter_flavorizr#100]
i have the below setup but when i run `flutter pub run flutter_flavorizr` its gives an error as 
`The following fields were missing: [ios]. Read the docs for further details`

which is not supposed to happen as i want to use my custom instructions not default ones this issue also mentioned at #63 where u not gave any reply

```
flavorizr:
  ide: vscode

  app:
    android:
      flavorDimensions: "flavor-type"

  flavors: 
    user:
      app:
        name: "User"

      android:
        applicationId: "com.example.user"

    admin:
      app:
        name: "Admin"

      android:
        applicationId: "com.example.admin"

  instructions:
    - assets:download
    - assets:extract
    - android:androidManifest
    - android:buildGradle
    - android:dummyAssets
    - android:icons
    - flutter:flavors
    - flutter:app
    - flutter:pages
    - flutter:targets
    # - ios:xcconfig
    # - ios:buildTargets
    # - ios:schema
    # - ios:dummyAssets
    # - ios:icons
    # - ios:plist
    # - ios:launchScreen
    - google:firebase
    - huawei:agconnect
    - assets:clean
    - ide:config
```

**Comment by AngeloAvv** [comment]
Hey @burhankhanzada , what happens if you try to put an iOS entry for each flavour without defining anything inside of it?

**Comment by Ahmadre** [comment]
just add:

```yaml
flavorizr:
  app:
    android:
      flavorDimensions: 'flavor-type'
    ios: null
```
