### ISSUE TITLE
resValues variable_one and variable_two is not populated to build.gradle

### ISSUE THREAD

**Issue by itwondersteam** [AngeloAvv/flutter_flavorizr#101]
pubspec.yaml used
```yaml
  flavors:
    apple:
      app:
        name: "Apple App"

      android:
        applicationId: "com.example.apple"
        resValues:
          variable_one:
            type: "string"
            value: "example variable one"
          variable_two:
            type: "string"
            value: "example variable two"

      ios:
        bundleId: "com.example.apple"
```

generated app/build.gradle
```gradle
android {

    // ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
    flavorDimensions "flavor-type"

    productFlavors {
        apple {
            dimension "flavor-type"
            applicationId "com.example.apple"
            resValue "string", "app_name", "Apple App"
        }
    }

    // ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----
```

Software used
```
Ubuntu 22.04 LTS
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
```
