### ISSUE TITLE
LoadError on ios instructions

### ISSUE THREAD

**Issue by Kleak** [AngeloAvv/flutter_flavorizr#104]
I'm trying to generate flavor for my iOS project but i got LoadError on all ios specific instructions

Here my flavorizr part of pubspec.yaml :
```yaml
flavorizr:    
  flavors:
    staging:
      app:
        name: "Staging"
      android:
        applicationId: "my.staging.app"
      ios:
        bundleId: "my.staging.app"
    
    production:
      app: 
        name: "Production"
      android:
        applicationId: "my.prod.app"
      ios:
        bundleId: "my.prod.app"
  
  instructions:
    - android:androidManifest
    - android:buildGradle
    - ios:xcconfig
    - ios:buildTargets
    - ios:schema
    - ios:plist
```

and here an example of the error :
`ruby: No such file or directory -- .tmp/scripts/ios/add_file.rb (LoadError)`

full error for ios:schema
```
Executing task ios:schema
Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/create_scheme.rb, ios/Runner.xcodeproj, staging
ruby: No such file or directory -- .tmp/scripts/ios/create_scheme.rb (LoadError)

Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/create_scheme.rb, ios/Runner.xcodeproj, production
ruby: No such file or directory -- .tmp/scripts/ios/create_scheme.rb (LoadError)
```

i have ruby installed
here is the output of `ruby -v`
`ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin21]`
