### ISSUE TITLE
iOS Config not working [APP NAME]

### ISSUE THREAD

**Issue by pbayog00** [AngeloAvv/flutter_flavorizr#113]
Everything is working fine for me when running on Android, but iOS is not working as expected (at least as I expect, maybe I am wrong). I am creating an app with two flavors, different app names and icons. Android shows both icons and names correctly, however, iOS just changes the icon, but shows the same name on both apps. To fix this, I have to change "Bundle display name" in Runner info config (xcode) to a User defined Setting, and manually give a name to each run config. 

Is this the expected behaviour or should flavorizr make this config for me (as it does on Android)?

Thx in advance for the help and congrats for the useful package!

I attach my flavorizr config on pubspec.yaml
```yaml
 flavorizr:

  ide: "idea"
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  flavors:
    parla:
      app:
        name: "Parla"
        icon: "assets/images/parla/logo.jpg"
      android:
        applicationId: "com.example.parla"
        icon: "assets/images/parla/logo.jpg"
      ios:
        bundleId: "com.example.parla"
        icon: "assets/images/parla/logo.jpg"
    zamora:
      app:
        name: "Zamora"
        icon: "assets/images/zamora/logo.jpg"
      android:
        applicationId: "com.example.zamora"
        icon: "assets/images/zamora/logo.jpg"
      ios:
        bundleId: "com.example.zamora"
        icon: "assets/images/zamora/logo.jpg"
```
