### ISSUE TITLE
Permissions issue when running flutter_flavorizr -p command. 

### ISSUE THREAD

**Issue by Scott-J-McMullan** [AngeloAvv/flutter_flavorizr#116]
Hello,

This package is great, thanks for creating & maintaining it.

I wanted to post this issue here because I'm trying to debug some weird behaviour in my project. Whenever I run the flavorizr command 
`flutter pub run flutter_flavorizr -p assets:download,assets:extract,google:firebase,android:buildGradle,android:androidManifest,ios:xcconfig,ios:buildTargets,ios:schema,ios:plist,assets:clean`
I must manually create some of the required directories. For instance, I must run

- mkdir .tmp 
- mkdir .tmp/ios
- mkdir .tmp/scripts 
- mkdir .tmp/scripts/ios/
-  mkdir android/app/src/[flavor]/res/mipmap-mdpi/
- mkdir android/app/src/[flavor]/res
- mkdir android/app/src/[flavor]/res/mipmap-mdpi/
- mkdir android/app/src/[flavor]/res/mipmap-hdpi
- mkdir android/app/src/[flavor]/res/mipmap-xhdpi
- mkdir android/app/src/[flavor]/res/mipmap-xxhdpi
- mkdir android/app/src/[flavor]/res/mipmap-xxxhdpi
- mkdir ios/Runner/Assets.xcassets/[flavor]AppIcon.appiconset/

before I can run the `flutter_flavorizr -p` because it will give me a file not found error. E.g.
`FileSystemException: Cannot open file, path = 'ios/Runner/Assets.xcassets/[flavor]AppIcon.appiconset/Icon-App-20x20@1x.png' (OS Error: No such file or directory, errno = 2)`

Is this an issue with my system? Or with the package? I can't run `flutter pub run flutter_flavorizr -p` with `sudo` as it says it's unsafe, so I'm not sure how to fix is.

System info:
Device: Mac Mini
OS: macOS Monterey 12.5.1 21G83
Flutter: Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-x64, locale en-AU
Flavorizr: ^2.1.4

Thanks.

**Comment by AngeloAvv** [comment]
Hello @Scott-J-McMullan , can you please provide the flutter_flavorizr configuration in your pubspec.yaml? Feel free to change the app identifiers if you want

**Comment by Scott-J-McMullan** [comment]
Hi @AngeloAvv,

Please see below:

```
flavorizr:
  assetsUrl: 'www.my-asset-url.com/assets.zip'
  flavors:
    stage:
      app:
        name: 'Stage'
      android:
        applicationId: 'com.project.stage'
        firebase:
          config: '.firebase/flavors/stage/google-services.json'
        icon: '.tmp/flavors/stage/images/icon-launch-android.png'
      ios:
        bundleId: 'com.project.stage'
        firebase:
          config: '.firebase/flavors/stage/GoogleService-Info.plist'
        icon: '.tmp/flavors/stage/images/icon-launch-ios.png'
```
