### ISSUE TITLE
Firebase Crashlytics just doesnt trigger errors

### ISSUE THREAD

**Issue by Hamdan85** [AngeloAvv/flutter_flavorizr#119]
Hey @AngeloAvv ,

I've researched a lot and didn't see anything about it so Im opening the issue. 

I've deleted android and ios folder, then
run `flutter create -i swift -a kotlin .`, then;
run `flutter pub run flutter_flavorizr`

using this pubspec config:
```
flavorizr:
  ide: "vscode"
  flavors:
    dev:
      app:
        name: "App Name"
      android:
        applicationId: "com.example.appname"
        icon: "assets/icons/onemob-icon.png"
        firebase:
          config: ".firebase/development/google-services.json"
      ios:
        bundleId: "com.onemob.mobiledevelopment"
        icon: "assets/icons/onemob-icon.png"
        firebase:
          config: ".firebase/development/GoogleService-Info.plist"
    production:
      app:
        name: "App Name"
      android:
        applicationId: "com.example.appname"
        icon: "assets/icons/onemob-icon.png"
        firebase:
          config: ".firebase/production/google-services.json"
      ios:
        bundleId: "com.onemob.mobile"
        icon: "assets/icons/onemob-icon.png"
        firebase:
          config: ".firebase/production/GoogleService-Info.plist"
```

Then I run an exception but nothing is registered to crashlytics. 
I've checked (with breakpoints) and it seems that all is correctly set in the flutter part... correct firebase settings. But for some reason, no crashs are reported on firebase. 

Do you have any idea of what might be happening?

Also, should I run flutterfire?? I did before but I think it got pretty messy and I've decided to start over, as I said, by cleaning everything.
