### ISSUE TITLE
archive 3.3.2

### ISSUE THREAD

**Issue by h-unterp** [AngeloAvv/flutter_flavorizr#135]
> Because flutter_flavorizr >=2.1.5 depends on archive ^3.3.2 and every version of flutter_driver from sdk depends on archive 3.3.0, flutter_flavorizr >=2.1.5 is incompatible with flutter_driver from sdk.
> So, because <my project> depends on both flutter_driver from sdk and flutter_flavorizr ^2.1.5, version solving failed.

my flutter:
```
Flutter is already up to date on channel stable
Flutter 3.3.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 6928314d50 (5 days ago) • 2022-10-25 16:34:41 -0400
Engine • revision 3ad69d7be3
Tools • Dart 2.18.2 • DevTools 2.15.0
```

**Comment by h-unterp** [comment]
same with integration_test package

```yaml
dev_dependencies:
  test: ^1.17.10
  flutter_test:
    sdk: flutter
  #integration_test:
  #  sdk: flutter
  #flutter_driver:
  #  sdk: flutter
  flutter_launcher_icons: ^0.10.0
  build_runner: ^2.1.10
  flutter_flavorizr: ^2.1.5
  freezed: ^2.0.3+1
```
