### ISSUE TITLE
Is there a way to share variables across flavors in pubspec.yaml?

### ISSUE THREAD

**Issue by kvenn** [AngeloAvv/flutter_flavorizr#142]
I have 4 flavors appDev, appProd, app2Dev, app2Prod. 
appDev and appProd should have the same `resValues` but different `applicationId`. app2Dev and app2Prod have everything different.

Is there a way to assign resValues to a variable so I don't need to update both configs each time?

```yaml
 appDev:
   app:
     name: "my app dev"
   android:
    applicationId: "com.app.dev"
     resValues:
       URL_SCHEME:
         type: "string"
         value: "app"
       CUSTOM_LINK:
         type: "string"
         value: "link.app.com"
         
  appProd:
   app:
     name: "my app"
   android:
    applicationId: "com.app"
     resValues:
       URL_SCHEME:
         type: "string"
         value: "app"
       CUSTOM_LINK:
         type: "string"
         value: "link.app.com"
```

**Comment by bschulz87** [comment]
Overrides are not working for me. Thus making the anchor useless. Used version 2.4.1

```
# flavorizr.yaml

x-buildSettings:
  buildSettings: &buildSettings
    FOO: "Foo"

flavors:
  test-app:
    ios:
      buildSettings:
        <<: *buildSettings
        DEVELOPMENT_TEAM: XYZ
```

Produces in project.pbxproj

```
...
buildSettings = {
  "<<" = {
    FOO = "Foo"
  }
  DEVELOPMENT_TEAM = XYZ
}
...
```
