### ISSUE TITLE
version solving failed. please update Image dependency

### ISSUE THREAD

**Issue by mayur-mindstack** [AngeloAvv/flutter_flavorizr#166]
am using flutter_native_splash and flutter_flavorizr in same project. its giving me  flutter_native_splash >=2.2.18 is
  incompatible with flutter_flavorizr 2.1.5.

**Comment by thingthing** [comment]
It seems that the code is in the repository, all it needs is to be published in pub.dev.

If you can´t wait for them to deploy @mayur-mindstack you can just use the git repository directly in your pubspec,
either the master branch directly:

```yaml
    git:
      url: https://github.com/AngeloAvv/flutter_flavorizr.git
      ref: master
```

or if you don´t want the new commits to break something you can use the last commit ref 

```yaml
    git:
      url: https://github.com/AngeloAvv/flutter_flavorizr.git
      ref: e056c41
```

it works for me
