### ISSUE TITLE
[iOS] unable to load contents of xcfilelist 

### ISSUE THREAD

**Issue by mduruisseau** [AngeloAvv/flutter_flavorizr#17]
Hello !

I tried to flavorize a small flutter project with two flavors, everything seems to work for Android, but I am unable to launch the app in the iOS Emulator.

I am getting these errors :
` error: Unable to load contents of file list: '/Target Support
    Files/Pods-Runner/Pods-Runner-frameworks-Debug *TARGET*-input-files.xcfilelist'
    (in target 'Runner' from project 'Runner')`

 `error: Unable to load contents of file list: '/Target Support
    Files/Pods-Runner/Pods-Runner-frameworks-Debug
    *TARGET*-output-files.xcfilelist' (in target 'Runner' from project 'Runner')`

I tried to clean the project, the pods and to rebuild everything without success.
The file `/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Debug *TARGET*-input-files.xcfilelist` seems to exists as I can see its content.

I didn't find any issue related to this kind of problem, could you help me understand what is going on ?

I am using Flutter 1.20.1, on macOS. Ruby, Gem and Xcodeproj are all up to date.

**Comment by AngeloAvv** [comment]
I need to investigate about that. I will try to setup a new project and check if everything works fine. It's possible that something has changed during the default Xcode project creation process in the last months.

**Comment by AngeloAvv** [comment]
Ok so I tried by flavorizing a new Flutter project starting from scratch, and it works out of the box in both Android and iOS configurations. 

I need you to be a little more patient with that, because I have to create a new project and add some pods, but I need more of your intel to understand what's going on. Did you flavorized your project before or after the creation of the dependencies from cocoapods?

Maybe the files that you say are available exist in the file system but are not referenced in the project so they don't get build?

**Comment by Nolence** [comment]
I ran into this same issue. Here were my steps:

1. `flutter create test_project`
2. Add flavors to yaml

```yaml
flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios:

  flavors:
    production:
      app:
        name: "Test"
      android:
        applicationId: "com.mytest.river"
      ios:
        bundleId: "com.mytest.river"
    development:
      app:
        name: "Test Dev"
      android:
        applicationId: "com.mytest.riverdev"
      ios:
        bundleId: "com.mytest.riverdev"
```

3. Add dev dependency

```yaml
dev_dependencies:
  flutter_flavorizr: ^1.0.9
```

4. `flutter pub get`
5. Run `flutter run --flavor development -t lib/main-development.dart`. It works and opens the app fine.
6. Add `google_fonts` to dependency list (or possibly any other library that adds native code)
7. Now run `flutter run --flavor development -t lib/main-development.dart` and get previous mentioned error
