### ISSUE TITLE
Misleading error message: `The following fields were missing: [ios]`

### ISSUE THREAD

**Issue by dJani97** [AngeloAvv/flutter_flavorizr#212]
When I tried to run the latest version of Flavorizr with an older config, I got this error:

```
The following fields were missing: [ios]. Read the docs for further details
```

Contrary to what the error says, the solution was to REMOVE the `ios` field from the beginning of the config.

So instead of this:

```yaml
app:
  android:
    flavorDimensions: "flavor-type"
  ios:
```

I had to use this:

```yaml
app:
  android:
    flavorDimensions: "flavor-type"
```

Or alternatively, I did get rid of the entire `app:` section anf Flavorizr still works fine. I like this solution the most.

I think this error message should be improved.

Also, the `2.2.0` changelog of _"Android and iOS definitions are no longer required"_ should contain something like:

_"**BREAKING**: must remove `ios` if it's unused."_
