### ISSUE TITLE
Build configuration on iOS uses space instead of -

### ISSUE THREAD

**Issue by vixez** [AngeloAvv/flutter_flavorizr#22]
The build script adds a space to the build configuration name, instead of a -

`Flutter expects a build configuration named Debug-#SCHEME_NAME`

Manually changing the name in Xcode fixes this.
I have opened a PR to fix this.

https://github.com/AngeloAvv/flutter_flavorizr/pull/21

**Comment by AngeloAvv** [comment]
I can't understand what's wrong with the space instead of the dash. If you setup an empty project and you follow my example it works out of the box.

Try setting up your project again, maybe you unwittingly changed some settings

**Comment by vixez** [comment]
I just tried a new project. With my config looking like this:

```
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    driver_staging_debug:
      app:
        name: "Get Driven Driver (S-D)"
      android:
        applicationId: "app.getdriven.driver.staging.debug"
      ios:
        bundleId: "app.getdriven.driver.staging.debug"
```

So I run

`flutter pub run flutter_flavorizr`

If you look at the iOS configurations in Xcode, you will see this:
<img width="513" alt="Screenshot 2020-08-31 at 10 14 48" src="https://user-images.githubusercontent.com/3032294/91698384-e50f3680-eb72-11ea-97fe-02b92d4dae7a.png">

`Debug driver_staging_debug` is invalid because there is a space, building will result in
```
The Xcode project defines build configurations: Debug, Release, Profile, Debug driver_staging_debug, Profile driver_staging_debug, Release driver_staging_debug
Flutter expects a build configuration named Debug-driver_staging_debug or similar.
Open Xcode to fix the problem:
  open ios/Runner.xcworkspace
1. Click on "Runner" in the project navigator.
2. Ensure the Runner PROJECT is selected, not the Runner TARGET.
3. Click the Editor->Add Configuration->Duplicate "Debug" Configuration.
```

Changing the name to `Debug-driver_staging_debug` and updating the schemes to the correct configuration, fixes this issue.
<img width="528" alt="Screenshot 2020-08-31 at 10 30 03" src="https://user-images.githubusercontent.com/3032294/91699709-fc4f2380-eb74-11ea-893f-67522a98ce76.png">
