### ISSUE TITLE
Flutter: Read variables defined in flavors

### ISSUE THREAD

**Issue by nikhil-thakkar** [AngeloAvv/flutter_flavorizr#232]
First of all thank you for this excellent package. This definitively makes life easier for developers.

I have a question about how to read the variables in flutter code which are defined in the flavors. For example
```
flavors:
  apple:
    app:
      name: "Apple App"
  
    android:
      applicationId: "com.example.apple"
      resValues:
        variable_one:
          type: "string"
          value: "example variable one"
        variable_two:
          type: "string"
          value: "example variable two"
  
    ios:
      bundleId: "com.example.apple"
      variables:
        variable_one:
          value: "variable1"
        variable_two:
          target: "Debug"
          value: "variable2"
```

How would I read the values for "variable_one" and "variable_two" in flutter code assuming the values will reflect as per platform? I couldn't find this answer in the readme file.
