### ISSUE TITLE
iOS app getting crashed on specific Flavor

### ISSUE THREAD

**Issue by vaibhavaroraneo** [AngeloAvv/flutter_flavorizr#260]
I am facing a strange issue of app crashes on iOS for `staging` and `preprod`. Only `prod` is getting run for simulators and devices. the error received is 

```
Terminating app due to uncaught exception 'com.firebase.core', reason: 'App name can only contain alphanumeric, hyphen (-), and underscore (_) characters'
```

The firebase files are updated with the names.  but somehow its getting crashed stating the same error.

The flavor code

```
flavorizr:
  app:
    android:
      flavorDimensions: "app_flavor"

  flavors:
    staging:
      app:
        name: " Staging"
      android:
        applicationId: "com.app.staging"
        firebase:
          config: "android/app/src/staging/google-services.json"
      ios:
        bundleId: "com.app.staging"
        firebase:
          config: "ios/config/staging/GoogleService-Info.plist"

    preprod:
      app:
        name: "PreProd"
      android:
        applicationId: "com.app.preprod"
        firebase:
          config: "android/app/src/preprod/google-services.json"
      ios:
        bundleId: "com.app.preprod"
        firebase:
          config: "ios/config/preprod/GoogleService-Info.plist"

    prod:
      app:
        name: "Prod"
      android:
        applicationId: "com.app.live"
        firebase:
          config: "android/app/src/prod/google-services.json"
      ios:
        bundleId: "com.app.live"
        firebase:
          config: "ios/config/prod/GoogleService-Info.plist"
```

@AngeloAvv can you please help?
