### ISSUE TITLE
PathNotFoundException: Cannot copy file to 'lib/app.dart', path = '.tmp/flutter/app.dart' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by dhavalchandegara** [AngeloAvv/flutter_flavorizr#284]
While setting up Flavorizr with the below YAML configuration, I was getting an error. 

Here is flavorizr.yaml configuration,
```
flavors:
  prod:
    app:
      name: "Demo App"
    android:
      applicationId: "com.demo.app"
    ios:
      bundleId: "com.demo.app"
    macos:
      bundleId: "com.demo.app"
  dev:
    app:
      name: "dev Demo App"
    android:
      applicationId: "com.demo.app.dev"
    ios:
      bundleId: "com.demo.app.dev"
    macos:
      bundleId: "com.demo.app.dev"
instructions:
  - flutter:flavors
  - android:buildGradle
  - flutter:app
  - flutter:main
  - ide:config
  - ios:podfile
  - ios:xcconfig
  - ios:schema
  - google:firebase
```

Here is the output of ```flutter pub run flutter_flavorizr``` this command, 

Error setting up flavors: Unhandled exception:
PathNotFoundException: Cannot copy file to 'lib/app.dart', path = '.tmp/flutter/app.dart' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.copySync (dart:io/file_impl.dart:366:5)
#2      CopyFileProcessor.execute (package:flutter_flavorizr/src/processors/commons/copy_file_processor.dart:43:26)
#3      Processor.execute (package:flutter_flavorizr/src/processors/processor.dart:144:24)

Is that, or am I missing something, or was I using or defining flavour in the wrong way?
