### ISSUE TITLE
Build flavors with different Firebase projects

### ISSUE THREAD

**Issue by sooxt98** [AngeloAvv/flutter_flavorizr#30]
Awesome package! @AngeloAvv , here's my suggestion for multiple firebase integration.

```
flavorizr:
  flavors:
    prod:
      firebase_config: creds/GoogleService-Info_Production.plist
      app_id: "com.example.prod"
    dev:
      firebase_config: creds/GoogleService-Info_Development.plist
      app_id: "com.example.dev"
```

with this config, the preprocessor can directly copy the creds plist to both ios and android path during build. and also i wish that there's a global `app_id` that can configure for both of the platform, thanks.
