### ISSUE TITLE
Issue when generating `manifestPlaceholders` with build.gradle.kts

### ISSUE THREAD

**Issue by abdallah-odeh** [AngeloAvv/flutter_flavorizr#315]
Hello there, 

thank you for your efforts,
There is an issue with generating `manifestPlaceholders` attribute

The currently generated is:
 `manifestPlaceholders = += ['appAuthRedirectScheme':'com.sanadcash.expense']`

while the correct is: 
 `manifestPlaceholders["appAuthRedirectScheme"] = "com.sanadcash.expense"`

here is my `flavorizr.yaml` content:
```
app:
  android:
    flavorDimensions: "default"

flavors:
  uat:
    app:
      name: "MyApp UAT"

    android:
      applicationId: "com.example.myapp"
      icon: "assets/app-icon-uat.png"
      customConfig:
        versionNameSuffix: "\"-uat\""
        manifestPlaceholders: += ['appAuthRedirectScheme':'uat.com.identity.myapp']
    ios:
      bundleId: "com.example.myapp"
      icon: "assets/app-icon-uat.png"

  prod:
    app:
      name: "Sanad Cash"

    android:
      applicationId: "com.example.myapp"
      icon: "assets/app-icon.png"
      customConfig:
        manifestPlaceholders: += ['appAuthRedirectScheme':'com.identity.myapp']
    ios:
      bundleId: "com.example.myapp"
      icon: "assets/app-icon.png"

ide: idea
```
