### ISSUE TITLE
Support iOS dark & tinted app icon variations

### ISSUE THREAD

**Issue by hamishjohnson** [AngeloAvv/flutter_flavorizr#329]
In iOS 18, you can have tinted and dark icons which require different asset types.

In flutter_launcher_icons, they are supported like so:

```
flutter_launcher_icons:
  ios: true
  image_path: source/app-icon.png
  image_path_ios_dark_transparent: source/app-icon-dark.png
  image_path_ios_tinted_grayscale: source/app-icon-tinted.png
```
