### ISSUE TITLE
macos workaround config for running directly from terminal/vscode

### ISSUE THREAD

**Issue by keitakun** [AngeloAvv/flutter_flavorizr#332]
A simple workaround to run/debug the macos flavor directly from terminal or vscode avoiding the 
`Library not loaded: @rpath/FlutterMacOS.framework/Versions/A/FlutterMacOS` error

> Currently, due to a bug in the Flutter SDK, it's not possible to run the macOS flavors from the terminal. You can run them from XCode by selecting the proper schema and by pressing play.

in flavorizr.yaml
```
flavors:
  apple:
    app:
      name: "Apple App"

    android:
      applicationId: "com.example.apple"  
    ios:
      bundleId: "com.example.apple"
    macos:
      bundleId: "com.example.apple"  
      buildSettings:
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
```

Adding `buildSettings` under `macos` like this and re-running `flutter pub run flutter_flavorizr` fixed the issue.
