### ISSUE TITLE
MacOS build fails: Unable to load contents of file list Pods-Runner-frameworks-Debug-dev-input-files.xcfilelist

### ISSUE THREAD

**Issue by bizz84** [AngeloAvv/flutter_flavorizr#335]
After flavoring my app and running the macos processors, I'm unable to run it on macOS.

**Update**: I managed to find a manual fix (read below), but this is something that should be done automatically by the `macos:xcconfig` processor.

## Reproduction steps

Clone this sample repo (ios,android have already been flavored):

```
git clone https://github.com/bizz84/flutter_ship_app
cd flutter_ship_app
git switch m03-macos-flavorizr
flutter pub get
```

Create the macos project:

```zsh
flutter create . --platform macos --org com.codewithandrea
```

Run the processors:

```
dart run flutter_flavorizr -p assets:download,assets:extract,macos:podfile,macos:xcconfig,macos:configs,macos:buildTargets,macos:schema,macos:plist,macos:dummyAssets,macos:icons,assets:clean
```

Run the app:

```
flutter run -d macos --flavor dev -t lib/main_dev.dart
```

Output:

```
Launching lib/main_dev.dart on macOS in debug mode...
Running pod install...                                           1,261ms
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006021-000C705A11C0201E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00006021-000C705A11C0201E, name:My Mac }
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
warning: Unable to read contents of XCFileList '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Debug-dev-output-files.xcfilelist' (in target 'Runner' from project 'Runner')
error: Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Debug-dev-input-files.xcfilelist' (in target 'Runner' from project 'Runner')
error: Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Debug-dev-output-files.xcfilelist' (in target 'Runner' from project 'Runner')
warning: Run script build phase '[CP] Embed Pods Frameworks' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
** BUILD FAILED **

Building macOS application...                                           
Error: Build process failed
```

If I run `ls macos/Pods/Target\ Support\ Files/Pods-Runner/`, I can see the files are there:

```
Pods-Runner-Info.plist                                      Pods-Runner-frameworks-Profile-output-files.xcfilelist      Pods-Runner.debug-dev.xcconfig
Pods-Runner-acknowledgements.markdown                       Pods-Runner-frameworks-Profile-prod-input-files.xcfilelist  Pods-Runner.debug-prod.xcconfig
Pods-Runner-acknowledgements.plist                          Pods-Runner-frameworks-Profile-prod-output-files.xcfilelist Pods-Runner.debug-stg.xcconfig
Pods-Runner-dummy.m                                         Pods-Runner-frameworks-Profile-stg-input-files.xcfilelist   Pods-Runner.debug.xcconfig
Pods-Runner-frameworks-Debug-dev-input-files.xcfilelist     Pods-Runner-frameworks-Profile-stg-output-files.xcfilelist  Pods-Runner.modulemap
Pods-Runner-frameworks-Debug-dev-output-files.xcfilelist    Pods-Runner-frameworks-Release-dev-input-files.xcfilelist   Pods-Runner.profile-dev.xcconfig
Pods-Runner-frameworks-Debug-input-files.xcfilelist         Pods-Runner-frameworks-Release-dev-output-files.xcfilelist  Pods-Runner.profile-prod.xcconfig
Pods-Runner-frameworks-Debug-output-files.xcfilelist        Pods-Runner-frameworks-Release-input-files.xcfilelist       Pods-Runner.profile-stg.xcconfig
Pods-Runner-frameworks-Debug-prod-input-files.xcfilelist    Pods-Runner-frameworks-Release-output-files.xcfilelist      Pods-Runner.profile.xcconfig
Pods-Runner-frameworks-Debug-prod-output-files.xcfilelist   Pods-Runner-frameworks-Release-prod-input-files.xcfilelist  Pods-Runner.release-dev.xcconfig
Pods-Runner-frameworks-Debug-stg-input-files.xcfilelist     Pods-Runner-frameworks-Release-prod-output-files.xcfilelist Pods-Runner.release-prod.xcconfig
Pods-Runner-frameworks-Debug-stg-output-files.xcfilelist    Pods-Runner-frameworks-Release-stg-input-files.xcfilelist   Pods-Runner.release-stg.xcconfig
Pods-Runner-frameworks-Profile-dev-input-files.xcfilelist   Pods-Runner-frameworks-Release-stg-output-files.xcfilelist  Pods-Runner.release.xcconfig
Pods-Runner-frameworks-Profile-dev-output-files.xcfilelist  Pods-Runner-frameworks.sh
Pods-Runner-frameworks-Profile-input-files.xcfilelist       Pods-Runner-umbrella.h
```

Note that if I run `pod install`, I get this:

```
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` in your build configuration (`Runner/Configs/AppInfo.xcconfig`).

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` in your build configuration (`Runner/Configs/AppInfo.xcconfig`).

...
```

## Solution

I managed to solve this by adding the correct includes to each of the *xcconfig files in `macos/Flutter`:

- `devDebug.xcconfig`

```
#include? "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug-dev.xcconfig"
#include "ephemeral/Flutter-Generated.xcconfig"
```

- `devProfile.xcconfig`

```
#include? "Pods/Target Support Files/Pods-Runner/Pods-Runner.profile-dev.xcconfig"
#include "ephemeral/Flutter-Generated.xcconfig"
```

... and so on for all 9 files.

Here's a diff with the fix on my project:

https://github.com/bizz84/flutter_ship_app/commit/80cb4376e0d773948ab6ea809911a42e5b958d4b

### pubspec.yaml

```yaml
dev_dependencies:
  ...
  flutter_flavorizr: 2.3.0

# Flutter Flavorizr
flavorizr:
  ide: "vscode"
  app:
    android:
      flavorDimensions: "flavor-type"
    
  flavors:
    dev:
      app:
        name: "Flutter Ship Dev"
      android:
        applicationId: "com.codewithandrea.flutter_ship_app.dev"
        icon: "assets/dev/app-icon.png"
        adaptiveIcon:
          foreground: "assets/dev/app-icon-foreground.png"
          background: "assets/android/app-icon-background.png"
      ios:
        bundleId: "com.codewithandrea.flutterShipApp.dev"
        icon: "assets/dev/app-icon.png"
      macos:
        bundleId: "com.codewithandrea.flutterShipApp.dev"
        icon: "assets/dev/app-icon.png"

    stg:
      app:
        name: "Flutter Ship Stg"
      android:
        applicationId: "com.codewithandrea.flutter_ship_app.stg"  
        icon: "assets/stg/app-icon.png"
        adaptiveIcon:
          foreground: "assets/stg/app-icon-foreground.png"
          background: "assets/android/app-icon-background.png"
      ios:
        bundleId: "com.codewithandrea.flutterShipApp.stg"
        icon: "assets/stg/app-icon.png"
      macos:
        bundleId: "com.codewithandrea.flutterShipApp.stg"
        icon: "assets/stg/app-icon.png"

    prod:
      app:
        name: "Flutter Ship"
      android:
        applicationId: "com.codewithandrea.flutter_ship_app"  
        icon: "assets/prod/app-icon.png"
        adaptiveIcon:
          foreground: "assets/prod/app-icon-foreground.png"
          background: "assets/android/app-icon-background.png"
      ios:
        bundleId: "com.codewithandrea.flutterShipApp"
        icon: "assets/prod/app-icon.png"
      macos:
        bundleId: "com.codewithandrea.flutterShipApp"
        icon: "assets/prod/app-icon.png"
```

### main_dev.dart

```dart
import 'main.dart';

// * Entry point for the dev flavor
void main() async {
  await runMainApp();
}
```

### main.dart

```dart
Future<void> runMainApp() async {
  WidgetsFlutterBinding.ensureInitialized();
  final container = ProviderContainer();
  // * Preload SharedPreferences before calling runApp, as the AppStartupWidget
  // * depends on it in order to load the themeMode
  await container.read(sharedPreferencesProvider.future);
  // run the app
  runApp(UncontrolledProviderScope(
    container: container,
    child: MainApp(),
  ));
}
```

### Flutter doctor

```text
[✓] Flutter (Channel stable, 3.29.2, on macOS 14.6.1 23G93 darwin-arm64, locale en-GB) [281ms]
    • Flutter version 3.29.2 on channel stable at /Users/andrea/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (5 weeks ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [1,089ms]
    • Android SDK at /Users/andrea/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1) [763ms]
    • Xcode at /Applications/Xcode-16.1.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [11ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2) [10ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.97.0) [9ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.104.0

[✓] Connected device (6 available) [5.9s]
    • sdk gphone64 arm64 (mobile)          • emulator-5554                        • android-arm64  • Android 15 (API 35) (emulator)
    • Andrea iPhone XR (wireless) (mobile) • 00008020-001231380AE1002E            • ios            • iOS 17.6.1 21G93
    • iPhone SE (3rd generation) (mobile)  • E868FDBB-79C4-443F-A818-2C0041923F74 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-1 (simulator)
    • macOS (desktop)                      • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop)      • mac-designed-for-ipad                • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome 135.0.7049.96

[✓] Network resources [194ms]
    • All expected network resources are available.

• No issues found!
```
