### ISSUE TITLE
macos: only first flavor is added to macos/Runner.xcodeproj/project.pbxproj

### ISSUE THREAD

**Issue by apetroaeiandrei** [AngeloAvv/flutter_flavorizr#347]
After setting up flavorizr.yaml with 2 flavors that include macos, project.pbxproj contains build configuration only for the first specified flavor, debug. I initially thought I was configuring something wrong, then switched the order of the flavors and I can confirm that the first flavor appears in pbxproj.

<img width="455" alt="Image" src="https://github.com/user-attachments/assets/4453bd43-3979-4ce5-9ecf-1bd4f735415f" />

### flavorizr.yaml

```yaml

app:
  android:
    flavorDimensions: "flavor-type"

instructions:
  - assets:download
  - assets:extract
  - google:firebase
  
  - android:buildGradle
  - android:androidManifest
  - android:icons

  - ios:xcconfig
  - ios:buildTargets
  - ios:schema
  - ios:icons
  - ios:launchScreen
  - ios:plist

  - macos:xcconfig
  - macos:buildTargets
  - macos:schema
  - macos:icons
  - macos:plist

  - ide:config
  - assets:clean


flavors:
  clujkart:
    app:
      name: "Cluj Kart"
      icon: "flavors/clujkart/launcher.jpg"
    android:
      applicationId: "com.kotsukotsu.racemanager.clujkart"
      icon: "flavors/clujkart/launcher.jpg"
    ios:
      bundleId: "com.kotsukotsu.racemanager.clujkart"
      icon: "flavors/clujkart/launcher.jpg"
    macos:
      bundleId: "com.kotsukotsu.racemanager.clujkart"
      icon: "flavors/clujkart/launcher.jpg"

  dev:
    app:
      name: "Race Dev"
    android:
      applicationId: "com.kotsukotsu.race_manager"
    ios:
      bundleId: "com.kotsukotsu.racemanager.raceManager"
    macos:
      bundleId: "com.kotsukotsu.racemanager.raceManager"

ide: vscode

``` 

### Flutter doctor
```
[✓] Flutter (Channel stable, 3.29.2, on macOS 15.5 24F74 darwin-arm64, locale en-US) [503ms]
    • Flutter version 3.29.2 on channel stable at /Users/andreiap/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (2 months ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0-rc1) [2.2s]
    • Android SDK at /Users/andreiap/Library/Android/sdk
    • Platform android-35, build-tools 36.0.0-rc1
    • ANDROID_HOME = /Users/andreiap/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/andreiap/Users/andreiap/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [1,510ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [13ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2) [12ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.100.2) [11ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (8 available) [6.9s]
    - removed

[✓] Network resources [4.9s]
    • All expected network resources are available.

• No issues found!
```
