### ISSUE TITLE
[Feature Request] Auto-detect Version from pubspec.yaml

### ISSUE THREAD

**Issue by CesareIsHere** [AngeloAvv/flutter_flavorizr#351]
### Summary

Add support for automatically reading version information from **_pubspec.yaml_** instead of requiring manual specification in each flavor configuration. This enhancement would complement the existing manual version specification, providing developers with flexibility to choose the method that best fits their workflow.

### Current Behavior

Version information must be manually specified for each flavor and platform in **flavorizr.yaml**:
```
flavors:
  production:
    android:
      versionCode: 1003000021
      versionName: "1.3.0"
    ios:
      variables:
        FLUTTER_BUILD_NUMBER:
          value: "1003000021"
        FLUTTER_BUILD_NAME:
          value: "1.3.0"
```

While the same version information already exists in **pubspec.yaml**:
`version: 1.3.0+1003000021`

### Proposed Enhancement

Add an optional configuration to automatically use version information from **pubspec.yaml** when parameters are not defined into **flavorizr.yaml**. Something like this:

```
usePubspecVersion: true

flavors:
  production:
    android:
      applicationId: "com.example.prod"
      # versionCode and versionName automatically read from pubspec.yaml
    ios:
      bundleId: "com.example.prod"
      # FLUTTER_BUILD_NUMBER and FLUTTER_BUILD_NAME automatically set
```

Thank you for considering this idea - I'd love to hear your feedback and would be happy to help with the implementation if you think it's useful!
