### ISSUE TITLE
Custom Icon and splash screen

### ISSUE THREAD

**Issue by sooxt98** [AngeloAvv/flutter_flavorizr#41]
It would be awesome to add dynamic icon and splash screen support as well 🎉

https://pub.dev/packages/flutter_native_splash
https://pub.dev/packages/flutter_launcher_icons

``` yaml
flavorizr:
  flavors:
    apple:
      app:
        name: "Apple App"

      android:
        applicationId: "com.example.apple"
        icon: "assets/images/apple_icon.png"
        firebase:
          config: ".firebase/apple/google-services.json"

      ios:
        bundleId: "com.example.apple"
        icon: "assets/images/apple_icon.png"
        firebase:
          config: ".firebase/apple/GoogleService-Info.plist"

```
