### ISSUE TITLE
"prod" flavor not working on iOS

### ISSUE THREAD

**Issue by ThomasEcalle** [AngeloAvv/flutter_flavorizr#48]
Hi,

First of all, thank you a lot for this package that is amazing in flavor handling.

I have tried this configuration :

```
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  flavors:
    dev:
      app:
        name: "App-dev"
      android:
        applicationId: "com.example.dev"
      ios:
        bundleId: "com.example.dev"

    preprod:
      app:
        name: "App-preprod"
      android:
        applicationId: "com.example.preprod"
      ios:
        bundleId: "com.example.preprod"

    prod:
      app:
        name: "App-prod"
      android:
        applicationId: "com.example.prod"
      ios:
        bundleId: "com.example.prod"
```

Everything works on both Android & iOS except `prod` flavor on iOS.

Building prod flavor on iOS throw this error :

```
The Xcode project defines build configurations: Debug, Release, Profile, Debug dev, Profile dev, Release dev, Debug preprod, Profile preprod, Release preprod, Debug prod, Profile prod, Release prod
Flutter expects a build configuration named Debug-prod or similar.
Open Xcode to fix the problem:
  open ios/Runner.xcworkspace
1. Click on "Runner" in the project navigator.
2. Ensure the Runner PROJECT is selected, not the Runner TARGET.
3. Click the Editor->Add Configuration->Duplicate "Debug" Configuration.

   If this option is disabled, it is likely you have the target selected instead
   of the project; see:
   https://stackoverflow.com/questions/19842746/adding-a-build-configuration-in-xcode

   If you have created a completely custom set of build configurations,
   you can set the FLUTTER_BUILD_MODE=debug
   in the .xcconfig file for that configuration and run from Xcode.

4. If you are not using completely custom build configurations, name the newly created configuration debug.
Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.
```

"dev" and "preprod" flavors are working well but not "prod".

Does someone have an idea of the issue ?

Thank you in advance !
