### ISSUE TITLE
A quick beginner question regarding flutter_flavorizr 

### ISSUE THREAD

**Issue by Hemshree** [AngeloAvv/flutter_flavorizr#5]
Hey there,
Really liked this flutter_flavorizr package to build flavours in Flutter. 👍 
I had one quick question: You have shown flavours in two different apps: Apple app and Banana app. Can you please tell how can we implement flavours on the same application. Like I need two different environments i.e. prod and dev environment for one single application. Do I need to make two different Firebase projects for running it in two different environments? And if yes, how can I add a same project as two different Firebase projects for getting two different appIds and Bundleids? 
Would be great if you could guide! 😄

**Comment by AngeloAvv** [comment]
Hi @Hemshree ,
If you are creating flavors based essentially on same package name but with different build destinations, I would suggest you to always create two flavors, but with the same package name: in this case the pubspec will look like this:

```
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "My App (For developers only)"

      android:
        applicationId: "com.example.app"

      ios:
        bundleId: "com.example.app"

    prod:
      app:
        name: "My App"

      android:
        applicationId: "com.example.app"
      ios:
        bundleId: "com.example.app"
```

If you need Firebase, you can create a single project with a single google-services.json. I guess you will need a single google-info.plist file too. I think you don't need to create two different package names or bundle ids for the very same app. Things start to be a little more tricky when you need firebase for different package names and bundle ids.
Anyway, I'm working on firebase related stuff, so I will add these features later.

I hope that this clarifies the issue.
