### ISSUE TITLE
Small issue: blank line added to build.gradæe every time I run the script

### ISSUE THREAD

**Issue by fabriziocacicia** [AngeloAvv/flutter_flavorizr#50]
## Description
Every time I run the script a blank line is added at the very end of the `android/app/build.gradle` file. 
Nothing critical but it could be annoying to have that file becoming very long due to blank lines after many executions.

## Steps to reproduce
I ran the script a first time with these configurations:

```yaml
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "AppName - Dev"
      android:
        applicationId: "app.web.domain.dev"
      ios:
        bundleId: "app.web.domain.dev"

    testing:
      app:
        name: "AppName - Test"
      android:
        applicationId: "app.web.domain.testing"
      ios:
        bundleId: "app.web.domain.testing"

    prod:
      app:
        name: "AppName"
      android:
        applicationId: "app.web.domain"
      ios:
        bundleId: "app.web.domain"

```
And I committed the changes removing manually the blank line at the end of the `android/app/build.gradle` file. 

Then I ran it a second time to add the Firebase configuration to the dev flavor:

```yaml
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "AppName - Dev"
      android:
        applicationId: "app.web.domain.dev"
        firebase:
          config: ".firebase/dev/google-services.json"
      ios:
        bundleId: "app.web.domain.dev"

    testing:
      app:
        name: "AppName - Test"
      android:
        applicationId: "app.web.domain.testing"
      ios:
        bundleId: "app.web.domain.testing"

    prod:
      app:
        name: "AppName"
      android:
        applicationId: "app.web.domain"
      ios:
        bundleId: "app.web.domain"

```
And I noticed that a new blank line was added. This time I left it there and I run again one time the script to add the Firebase configs to the test flavor. And again a new blank line was added.
So I run a third time the script to add the Firebase configs for the prod flavor and a fourth time without adding anything new.

These are two screenshot, taken after the four consecutive executions of the script, to show where the lines are added
<img width="609" alt="Screenshot 2021-05-01 at 11 43 33" src="https://user-images.githubusercontent.com/7525888/116778487-79b79480-aa72-11eb-8d17-eb10bdd2847c.png">
<img width="584" alt="Screenshot 2021-05-01 at 11 43 57" src="https://user-images.githubusercontent.com/7525888/116778498-863bed00-aa72-11eb-80fe-598a29d8c979.png">
