### ISSUE TITLE
Only on Android

### ISSUE THREAD

**Issue by ramezaniivar** [AngeloAvv/flutter_flavorizr#63]
Hi
First of all, thank you very much for your good library

I want to use the library only on Android
please guide me

**Comment by ramezaniivar** [comment]
![Untitsled](https://user-images.githubusercontent.com/59112188/128611318-99e8701a-6d4d-406d-b7fd-b4d6485cf601.jpg)

**Comment by AngeloAvv** [comment]
Hello @ramezaniivar , you have to use a custom instruction set without including the ios instructions. See [available instructions](https://github.com/AngeloAvv/flutter_flavorizr#available-instructions) for further details.

Duplicate of #45

**Comment by Yallan** [comment]
Hello @AngeloAvv, i have an Android only flutter project and when i run flutter_flavorizr without iOS instructions, i have this error : 
```
Unhandled exception:
Error reading from ios/Runner/Info.plist. The file does not exist
```
Is it possible to run on an Android only flutter project ?
Thanks

**Comment by AngeloAvv** [comment]
Hello @Yallan , can you please attach your flavorizr config?

**Comment by Yallan** [comment]
```
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  flavors:
    local:
      app:
        name: "Local"
      android:
        applicationId: "com.company.app.local"
        icon: "assets/images/icon-local.png"
      ios:
        bundleId: ""
    preprod:
      app:
        name: "Preprod"
      android:
        applicationId: "com.company.app.preprod"
        icon: "assets/images/icon-preprod.png"
      ios:
        bundleId: ""
    prod:
      app:
        name: "Prod"
      android:
        applicationId: "com.company.app"
        icon: "assets/images/icon-prod.png"
      ios:
        bundleId: ""
  instructions: 
    - android:androidManifest
    - android:buildGradle
    - android:dummyAssets
    - android:icons
    - flutter:flavors
    - flutter:app
    - flutter:targets
```
