### ISSUE TITLE
Unable to run application on iOS

### ISSUE THREAD

**Issue by hvg2416** [AngeloAvv/flutter_flavorizr#64]
My steps:

1. Add flutter_flavorizr: ^2.0.0 in dev_dependencies in the pubspec.yml file
2. Add flavorizr config in pubspec.yml file
```
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    apple:
      app:
        name: "Apple App"

      android:
        applicationId: "com.volumestories.flutterapp"

      ios:
        bundleId: "com.volumestories.flutterapp"

    banana:
      app:
        name: "Banana App"

      android:
        applicationId: "com.example.banana"
      ios:
        bundleId: "com.example.banana"
```
3. Run `flutter pub run flutter_flavorizr` command in terminal
4. Run `flutter run --flavor apple -t lib/main-apple.dart` in the terminal targeting ios simulator

**Output of terminal**:
![Screenshot 2021-09-13 at 10 37 58 PM](https://user-images.githubusercontent.com/49445823/133126936-a3deb134-fcbf-4835-a4d0-611d8aa5bea6.png)

Please help me resolve this issue.

_Note: I am able to run the same application using flutter_flavorizr in android_
