### ISSUE TITLE
Firebase on IOS

### ISSUE THREAD

**Issue by p02diada** [AngeloAvv/flutter_flavorizr#65]
Hi, I have a project using this awesome package and now I want to add a firebase integration. I'm trying to use only the firebase command because I don't want to overwrite my configurations but the script is not added to the build phases. The command does not show any errors:

```
fvm flutter pub run flutter_flavorizr -p assets:download,assets:extract,google:firebase,assets:clean
Executing task assets:download

Executing task assets:extract

Executing task google:firebase
Running AndroidFirebaseProcessor
Running AndroidTargetFirebaseProcessor
Running NewFolderProcessor: Creating directory android/app/src/beta
Running Copying file from ./firebase/android/beta/google-services.json to android/app/src/beta/google-services.json
Running AndroidTargetFirebaseProcessor
Running NewFolderProcessor: Creating directory android/app/src/live
Running Copying file from ./firebase/android/beta/google-services.json to android/app/src/live/google-services.json
Running IOSTargetsFirebaseProcessor
Running IOSFirebaseProcessor
Running NewFolderProcessor: Creating directory ios/Runner/beta
Running Copying file from ./firebase/apple/beta/GoogleService-Info.plist to ios/Runner/beta/GoogleService-Info.plist
Running IOSFirebaseProcessor
Running NewFolderProcessor: Creating directory ios/Runner/live
Running Copying file from ./firebase/apple/beta/GoogleService-Info.plist to ios/Runner/live/GoogleService-Info.plist
Running FileProcessor: writing file ios/Runner/GoogleService-Info.plist with nested EmptyFileProcessor
Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/add_file.rb, ios/Runner.xcodeproj, Runner/GoogleService-Info.plist
Running FileProcessor: writing file .tmp/ios/firebaseScript.sh with nested IOSFirebaseScriptProcessor
Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/add_firebase_build_phase.rb, ios/Runner.xcodeproj, .tmp/ios/firebaseScript.sh

Executing task assets:clean
Running Deleting file from assets.tmp.zip
Running Deleting file from .tmp
```
 
 
![image](https://user-images.githubusercontent.com/6508269/140081395-38937774-fb89-4cca-a125-ac7ddc8ce439.png)

**Comment by AngeloAvv** [comment]
Hello @p02diada , can you please provide your flavorizr section from the pubspec.yaml file? Did you install ruby, gem and xcodeproj?

**Comment by p02diada** [comment]
Hello, of course I can share

```
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    beta:
      app:
        name: "Example - Beta"

      android:
        applicationId: "com.example.clients.beta"
        firebase:
          config: "./firebase/android/beta/google-services.json"

    live:
      app:
        name: "Example"

      android:
        applicationId: "com.example.clients.live"
        firebase:
          config: "./firebase/android/beta/google-services.json"
```

And these are my installed versions:
```
ruby -v            
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

gem -v             
3.2.22

xcodeproj --version
1.21.0
```

**Comment by enpiech** [comment]
I have same issues

**Comment by sanekyy** [comment]
Hello @AngeloAvv 
I just start using your package and faced with same issue for iOS.
Could you check this issue please?

Configuration:
```yaml
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    meditivity:
      app:
        name: "Meditivity"

      android:
        applicationId: "com.meditivity.app"
        firebase:
          config: ".firebase/meditivity/google-services.json"
      ios:
        bundleId: "com.meditivity.app"
        firebase:
          config: ".firebase/meditivity/GoogleService-Info.plist"

    essence:
      app:
        name: "Essence"

      android:
        applicationId: "app.theessence.android"
        firebase:
          config: ".firebase/essence/google-services.json"
      ios:
        bundleId: "app.theessence.iosapp"
        firebase:
          config: ".firebase/essence/GoogleService-Info.plist"

```

Output: 
```
flutter pub run flutter_flavorizr -p google:firebase
Executing task google:firebase
Running AndroidFirebaseProcessor
Running AndroidTargetFirebaseProcessor
Running NewFolderProcessor: Creating directory android/app/src/meditivity
Running Copying file from .firebase/meditivity/google-services.json to android/app/src/meditivity/google-services.json
Running AndroidTargetFirebaseProcessor
Running NewFolderProcessor: Creating directory android/app/src/essence
Running Copying file from .firebase/essence/google-services.json to android/app/src/essence/google-services.json
Running IOSTargetsFirebaseProcessor
Running IOSFirebaseProcessor
Running NewFolderProcessor: Creating directory ios/Runner/meditivity
Running Copying file from .firebase/meditivity/GoogleService-Info.plist to ios/Runner/meditivity/GoogleService-Info.plist
Running IOSFirebaseProcessor
Running NewFolderProcessor: Creating directory ios/Runner/essence
Running Copying file from .firebase/essence/GoogleService-Info.plist to ios/Runner/essence/GoogleService-Info.plist
Running FileProcessor: writing file ios/Runner/GoogleService-Info.plist with nested EmptyFileProcessor
Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/add_file.rb, ios/Runner.xcodeproj, Runner/GoogleService-Info.plist
ruby: No such file or directory -- .tmp/scripts/ios/add_file.rb (LoadError)

Running FileProcessor: writing file .tmp/ios/firebaseScript.sh with nested IOSFirebaseScriptProcessor
Unhandled exception:
FileSystemException: Cannot open file, path = '.tmp/ios/firebaseScript.sh' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      AbstractFileStringProcessor.execute (package:flutter_flavorizr/processors/commons/abstract_file_string_processor.dart:42:15)
#5      QueueProcessor.execute (package:flutter_flavorizr/processors/commons/queue_processor.dart:43:17)
#6      QueueProcessor.execute (package:flutter_flavorizr/processors/commons/queue_processor.dart:43:17)
#7      Processor.execute (package:flutter_flavorizr/processors/processor.dart:112:24)
#8      execute (package:flutter_flavorizr/flutter_flavorizr.dart:55:13)
#9      main (file:///Users/sanekyy/Programs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_flavorizr-2.1.2/bin/flutter_flavorizr.dart:4:3)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255

```
