### ISSUE TITLE
Dependency conflict with integration_test

### ISSUE THREAD

**Issue by JChrist** [AngeloAvv/flutter_flavorizr#67]
Updating to the latest version `flutter_flavorizr: ^2.1.0` causes a version solving failure with the sdk `integration_test` package:
```yml
dev_dependencies:
  flutter_flavorizr: ^2.1.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
```

With this config, when trying to fetch dependencies with `flutter pub get`, a version solving error is shown:
```
Because every version of integration_test from sdk depends on archive 3.1.2 and flutter_flavorizr >=2.1.0 depends on archive ^3.1.6, integration_test from sdk is incompatible with flutter_flavorizr >=2.1.0.
So, because my_app depends on both flutter_flavorizr ^2.1.0 and integration_test any from sdk, version solving failed.
```
