### ISSUE TITLE
Flavors file doesn't get updated with environment variables

### ISSUE THREAD

**Issue by dorsamet** [AngeloAvv/flutter_flavorizr#76]
Hello,
I am trying to run the `flutter pub run flutter_flavorizr` command, when having this in the `pubspec.yaml`

```
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "App Name"

      android:
        applicationId: "com.app.name"
        resValues:
          places_api_key:
            type: "string"
            value: "some string"
```

It seems as though the `flavors.dart` doesn't get updated, but I might be setting up something wrong

Can anyone assist?
