### ISSUE TITLE
android splash new API in 12

### ISSUE THREAD

**Issue by xpwmaosldk** [AngeloAvv/flutter_flavorizr#79]
Now, Android is using icon in splash.
https://developer.android.google.cn/about/versions/12/features/splash-screen

Usually there is no problem, but mismatch in case of dark theme
So, I need some customize splash both ios and android for same looks

```
flavors:
    prod:
      app:
        name: "apple"
        icon: "images/launch_icon.png"
        splash_background_color: "#FFFFFF" // like this or _dark or etc..
```
