### ISSUE TITLE
[Doc] flavorDimensions is not marked as required in the documentation

### ISSUE THREAD

**Issue by nicopico-dev** [AngeloAvv/flutter_flavorizr#80]
In README.md, all samples set the `flavorDimensions` property:

```
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
```

but the [table](https://github.com/AngeloAvv/flutter_flavorizr/blob/master/README.md#android-under-app) say that this parameter is *not* required

However if the property is not defined, flavorizr fails to run:
```
$ flutter pub run flutter_flavorizr
The following fields were missing: [android]. Read the docs for further details
```

The documentation should reflect that this property is required (and the error message was not very helpful here)
