### ISSUE TITLE
I need AndroidManifest each flavor

### ISSUE THREAD

**Issue by xpwmaosldk** [AngeloAvv/flutter_flavorizr#81]
Hi there
My flaovr configuration is here
```
flavors:
    prod:
      app:
        name: "myapp"
      android:
        applicationId: "com.myapp"
      ios:
        bundleId: "com.myapp"

    dev:
      app:
        name: "myapp-dev"
      android:
        applicationId: "com.myapp.dev"
      ios:
        bundleId: "com.myapp.dev"
```
This flavors is use same AndroidManifest right?
The google oauth configuration required the package name in AndroidManifest not applicationId.
so I made manually made each AndroidManifest for flavor.
can you make this feature?

**Comment by andre-stefanov** [comment]
You could use manifest placeholders to achieve this in android: https://developer.android.com/studio/build/manage-manifests#inject_build_variables_into_the_manifest

**Comment by AngeloAvv** [comment]
Thank you @andre-stefanov for providing a solution to this issue

**Comment by kvenn** [comment]
How I did it:
```yaml
      android:
        applicationId: "com.test.test.dev"
        customConfig:
          manifestPlaceholders.altSubdomain: = "subdomain"
```
