### ISSUE TITLE
Android other properties flavors

### ISSUE THREAD

**Issue by JonathanAJ** [AngeloAvv/flutter_flavorizr#88]
Hello @AngeloAvv 

There are way to make custom android properties? Like:

```groovy
flavor_name {
            dimension "my_dimension"
            applicationId "com.flavor"
            applicationIdSuffix ".flavor_name" <---- I NEDD THIS LINE
            versionNameSuffix "-flavor_name-prod" <---- I NEDD THIS LINE
            signingConfig flavorSigning.flavor_name <---- I NEDD THIS LINE
        }
```

Maybe the yml to generate this could be something this:

```yml
...
flavor_name
    android:
            applicationId: "com.flavor"
            customConfig:
                applicationIdSuffix:  "\".flavor_name\""
                versionNameSuffix: "\"-flavor_name-prod\""
                signingConfig: "flavorSigning.flavor_name"
```

Please, this really turn development of advanced properties in android more productive!
