### ISSUE TITLE
How to use flutter:targets

### ISSUE THREAD

**Issue by danielRi** [AngeloAvv/flutter_flavorizr#90]
Hi,

I have the follow scenario: I have a code base that needs to ship with 7 different Titles and Icons

-> Can be solved with flavors, works fine.

But each flavor needs to have different target builds, e.G. test, staging, production etc...
Each target has own URLs for server endpoints (custom variables?)
So you would have a 2D array of flavor/targets, if you want. 7 Flavors (doc, grumpy, bashful, etc..), with each flavor has 3 Targets (test, production, etc..), resulting in a combination of 21 different builds.

How to solve that?

The docu says about targets:

flutter:targets | Flutter | Creates a set of targets for each flavor instance
-- | -- | --

But how to use it? So far I tried this. If targets dont work, what can I use for my problem?

```
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    doc:
      app:
        name: "Doc"
    grumpy:
      app:
        name: "Grumpy"
    bashful:
      app:
        name: "Bashful"
    ...

  targets:
    test:
    staging:
    production:
```

**Comment by JonathanAJ** [comment]
hey, 

So... basically, in a pure android project you could use a set of dimensions (Android).

this repo only allow to use one dimension in android project....

but....

you could create something like:

```yml
flavors:
    doc-test:
      app:
        name: "Doc Test"

    doc-dev:
      app:
        name: "Doc Dev"

    doc-production:
      app:
        name: "Doc Prod"
```
