### ISSUE TITLE
Fail to run on iOS: Unable to load contents of file list: '/Target Support Files/Pods-Runner/...

### ISSUE THREAD

**Issue by dJani97** [AngeloAvv/flutter_flavorizr#96]
When trying to run or build on iOS, I get the following errors:

```
# flutter build ipa --flavor dev -t lib/main_dev.dart

Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Debug-dev-input-files.xcfilelist'
Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Debug-prod-output-files.xcfilelist'
```

Seems like it's looking for some **flavor-specific files**, but my project's `ios/Pods/Target Support Files/Pods-Runner/` folder only has the following variants:
- Pods-Runner-frameworks-Debug-input-files.xcfilelist
- Pods-Runner-frameworks-Debug-output-files.xcfilelist
- Pods-Runner-frameworks-Profile-input-files.xcfilelist
- Pods-Runner-frameworks-Profile-output-files.xcfilelist
- Pods-Runner-frameworks-Release-input-files.xcfilelist
- Pods-Runner-frameworks-Release-output-files.xcfilelist

Deleting and recreating the Pods folder doesn't help.

Is there any way to overcome this problem?

---------
Although I'm not sure if useful, here's a bit more info:
---------

The relevant part of my YAML:

```yaml
flavorizr:
  ide: "idea"
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "App DEV"

      android:
        applicationId: "com.example.mobile.dev"
        generateDummyAssets: false
        customConfig:
          versionNameSuffix: "\"-dev\""

      ios:
        bundleId: "com.example.mobile.dev"
        generateDummyAssets: false
        buildSettings:
          DEVELOPMENT_TEAM: EXAMPLETEAM
          PROVISIONING_PROFILE_SPECIFIER: ""
```

And in Xcode it's visible that my flavors got generated:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/22769564/161464742-088634de-bce2-4ab4-8179-cfe5b56c2e8d.png">
